import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '@/components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mi Portafolio!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://mi-portafolio-martello.vercel.app/_next/image?url=%2FLogo.png&w=96&q=75"></link>
      </Head>
      <div>
        <Main />
        <About />
        <Skills />
        <Projects />
        <Contact />
      </div>
    </>
  )
}
